const header=document.querySelector('.site-header');const nav=document.querySelector('.nav');const toggle=document.querySelector('.nav-toggle');const links=[...document.querySelectorAll('.nav a')];
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>24));
toggle.addEventListener('click',()=>{const open=toggle.classList.toggle('open');nav.classList.toggle('open',open);toggle.setAttribute('aria-expanded',open)});links.forEach(a=>a.addEventListener('click',()=>{toggle.classList.remove('open');nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.style.transitionDelay=`${e.target.dataset.delay||0}ms`;e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const sections=[...document.querySelectorAll('main section[id]')];const activeObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-38% 0px -58%'});sections.forEach(s=>activeObserver.observe(s));
const stats=document.querySelectorAll('[data-count]');const statObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target,target=Number(el.dataset.count),dec=Number(el.dataset.decimals||0),suffix=el.dataset.suffix||'',duration=1500,start=performance.now();const tick=now=>{const p=Math.min((now-start)/duration,1),ease=1-Math.pow(1-p,3);el.textContent=(target*ease).toFixed(dec)+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);statObserver.unobserve(el)}),{threshold:.6});stats.forEach(s=>statObserver.observe(s));
const tabs=document.querySelectorAll('.skill-tab');tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});document.querySelectorAll('.skill-panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');tab.setAttribute('aria-selected','true');document.getElementById(tab.dataset.tab).classList.add('active')}));
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
const hero=document.querySelector('.hero-visual');const floaters=document.querySelectorAll('.floating-tech');if(hero){hero.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/r.width,y=(e.clientY-r.top-r.height/2)/r.height;floaters.forEach(f=>{const d=Number(f.dataset.depth||1);f.style.marginLeft=`${x*18*d}px`;f.style.marginTop=`${y*18*d}px`})});hero.addEventListener('pointerleave',()=>floaters.forEach(f=>{f.style.marginLeft='0';f.style.marginTop='0'}))}
document.getElementById('year').textContent=new Date().getFullYear();
